'use client';
import {useEffect,useState} from 'react';
import {modules,types,flows,actions,batchCost,type State,type Row,type Field} from '@/lib/erp';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {ThemeToggle} from '@/components/theme-toggle';
import {LayoutDashboard,FlaskConical,Package,Factory,ShoppingCart,Users,CalendarDays,ClipboardCheck,ShieldCheck,Boxes,Wrench,Truck,Route,Wallet,Files,Landmark,Search,Plus,Download,ChevronRight,ArrowUpRight,Clock,Check,Activity,RefreshCw,FileText,HelpCircle,CheckCircle2,AlertTriangle,Layers,MoreHorizontal} from 'lucide-react';
const icons:any={dashboard:LayoutDashboard,products:FlaskConical,suppliers:Users,procurement:ShoppingCart,inventory:Boxes,planning:CalendarDays,batches:Factory,packaging:Package,qc:ClipboardCheck,qa:ShieldCheck,equipment:Wrench,sales:Truck,recalls:Route,finance:Wallet,documents:Files,regulatory:Landmark,audit:Activity};
const groups=[{label:'WORKSPACE',keys:['dashboard']},{label:'MANUFACTURING',keys:['products','planning','batches','packaging','equipment']},{label:'SUPPLY CHAIN',keys:['procurement','suppliers','inventory','sales']},{label:'QUALITY & GOVERNANCE',keys:['qc','qa','recalls','documents','regulatory']},{label:'BUSINESS',keys:['finance','audit']}];
const money=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
const fmt=(v:any)=>Number(v||0).toLocaleString();
function Status({value}:{value:string}){const color=value==='In production'?'production':value==='Dispatched'?'shipped':['Approved','Released','Passed','Ready','Completed','Paid','Acknowledged','Closed','Dispatched'].includes(value)?'good':['Rejected','Failed','Recalled','Suspended','Expired','Out of service'].includes(value)?'bad':['Pending','Awaiting QC','Quarantine','Investigating','Maintenance','Open'].includes(value)?'warn':'neutral';return <span className={'status '+color}><span/>{value}</span>}
function Picker({value,onChange,options,placeholder='Choose an option'}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];placeholder?:string}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.filter(x=>x.value).map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function Page(){
const [state,setState]=useState<State|null>(null),[version,setVersion]=useState(0),[page,setPage]=useState('dashboard'),[role,setRole]=useState('Operations'),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[type,setType]=useState('All'),[selected,setSelected]=useState<{module:string;id:string}|null>(null),[form,setForm]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[trace,setTrace]=useState('BTH-2601'),[help,setHelp]=useState(false);
const load=async()=>{try{setError('');const r=await fetch('/api/erp');const d:any=await r.json();if(!r.ok)throw Error(d.error);setState(d.state);setVersion(d.version);}catch(e){setError((e as Error).message)}};
useEffect(()=>{load();const h=location.hash.slice(1);if(modules[h]||h==='audit')setPage(h)},[]);
const nav=(p:string)=>{setPage(p);setSearch('');setFilter('All');setType('All');location.hash=p;};
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'navigate_erp_module',description:'Open an ERP module without changing records',inputSchema:{type:'object',properties:{module:{type:'string',enum:['dashboard',...Object.keys(modules),'audit']}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!modules[input.module]&&!['dashboard','audit'].includes(input.module))throw Error('Unknown module');nav(input.module);return {module:input.module};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
const save=async(module:string,action:string,recordId?:string,data:any={})=>{setBusy(true);try{const r=await fetch('/api/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module,action,recordId,data,role,version})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setState(d.state);setVersion(d.version);setForm(null);toast.success(action==='Create'?'Record created':action==='Edit'?'Changes saved':action+' completed');return true;}catch(e){toast.error((e as Error).message);return false;}finally{setBusy(false)}};
const records=state?.records||{};
const lookup=(m:string,id:string)=>records[m]?.find(x=>x.id===id);
const record=selected?lookup(selected.module,selected.id):undefined;
const open=(module:string,r:Row)=>setSelected({module,id:r.id});
const newForm=(module:string,row?:Row,revision=false)=>{let data:any=row?{...row}:{};for(const f of modules[module].fields)if(!data[f.key]&&f.options)data[f.key]=f.options[0];if(revision){data.name=row!.name+' (revision)';data.version=String(Number(row!.version||1)+1);}setForm({module,action:row&&!revision?'Edit':'Create',id:row&&!revision?row.id:undefined,data})};
const doAction=(module:string,r:Row,a:string)=>{if(['Record next step','Transfer','Activate recall','Reject','Fail','Dispatch','Return','Release'].includes(a))setForm({module,action:a,id:r.id,data:{},name:r.name});else save(module,a,r.id)};
const exportRows=(rows:Row[])=>{const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r)))).filter(k=>rows.some(r=>typeof r[k]!=='object'));const csv=[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv'}));a.download=page+'-export.csv';a.click();URL.revokeObjectURL(a.href)};
let rows=page==='audit'?state?.audit||[]:records[page]||[];
rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())&&(filter==='All'||r.status===filter)&&(type==='All'||r.type===type||lookup('products',r.product)?.type===type));
const module=modules[page];const title=page==='dashboard'?'Operations overview':page==='audit'?'Audit history':module?.title;
const table=(m:string,items:Row[],compact=false)=><Table><TableHeader><TableRow><TableHead>{m==='audit'?'Activity':'Record'}</TableHead><TableHead>{m==='batches'?'Manufacturing type':m==='inventory'?'Location':m==='sales'?'Product':m==='finance'?'Type':'Reference'}</TableHead><TableHead>{['inventory','batches','planning','sales','procurement'].includes(m)?'Quantity':m==='finance'?'Amount':'Date / owner'}</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.length?items.map(r=><TableRow key={r.id} onClick={()=>m!=='audit'&&open(m,r)} className={m!=='audit'?'clickable':''}><TableCell><strong>{r.name}</strong><small className="mono">{r.id}</small></TableCell><TableCell>{m==='batches'?lookup('products',r.product)?.type:m==='inventory'?r.location||'Unassigned':m==='sales'?lookup('products',r.product)?.name:m==='finance'?r.kind:m==='audit'?r.role:r.target||r.batch||r.version&&'Version '+r.version||r.category||r.market||r.product&&lookup('products',r.product)?.name||'—'}</TableCell><TableCell>{['inventory','batches','planning','sales','procurement'].includes(m)?<span className="numeric">{fmt(r.quantity)} <span className="muted">{r.unit||lookup('products',r.product)?.unit||''}</span></span>:m==='finance'?money(r.amount):r.due||r.expiry||r.at?.slice(0,16).replace('T',' ')||r.owner||'—'}</TableCell><TableCell><Status value={r.status}/></TableCell><TableCell>{m!=='audit'&&<button className="iconbutton" onClick={e=>{e.stopPropagation();open(m,r)}} aria-label={'Open '+r.name}><ChevronRight size={17}/></button>}</TableCell></TableRow>):<TableRow><TableCell colSpan={5}><div className="empty"><Layers size={30}/><strong>No matching records</strong><p>{search||filter!=='All'?'Try changing the search or filter.':'Create a record to begin this workflow.'}</p></div></TableCell></TableRow>}</TableBody></Table>;
const alertItems=[{title:'Batches awaiting quality release',count:records.batches?.filter(r=>r.status==='Awaiting QC').length||0,module:'batches',desc:'Review test results and packaging records',icon:ClipboardCheck},{title:'Open quality investigations',count:records.qa?.filter(r=>r.status!=='Closed').length||0,module:'qa',desc:'Resolve deviations and corrective actions',icon:ShieldCheck},{title:'Purchase orders in transit',count:records.procurement?.filter(r=>r.status==='Ordered').length||0,module:'procurement',desc:'Receive materials into quarantine',icon:Truck}];
const traceBatch=lookup('batches',trace);
return <SidebarProvider style={{'--sidebar-width':'248px'} as any}><Toaster position="top-right"/><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><div className="brandmark">p</div><div>pharmora<span>MANUFACTURING ERP</span></div></div><div className="workspace"><div className="workspaceIcon"><Factory size={17}/></div><div><strong>Manufacturing HQ</strong><small>Demo workspace</small></div><span className="workspaceTag">PRO</span></div></SidebarHeader><SidebarContent>{groups.map(g=><SidebarGroup key={g.label}><SidebarGroupLabel>{g.label}</SidebarGroupLabel><SidebarMenu>{g.keys.map(k=>{const Icon=icons[k];return <SidebarMenuItem key={k}><SidebarMenuButton isActive={page===k} onClick={()=>nav(k)} tooltip={modules[k]?.short||k}><Icon size={18}/><span>{k==='dashboard'?'Overview':k==='audit'?'Audit history':modules[k].short}</span>{k==='qc'&&<span className="navcount">{records.qc?.filter(r=>r.status==='Pending').length||0}</span>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><button className="helpbutton" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Prototype guide<ChevronRight size={14}/></button><div className="profile"><span className="avatar">SA</span><div><strong>Workspace owner</strong><small>All demo departments</small></div></div></SidebarFooter></Sidebar><SidebarInset className="main"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><strong>{page==='dashboard'?'Overview':module?.short||'Audit history'}</strong></div><div className="topright"><span className="prototypeTag">Interactive prototype</span><ThemeToggle/><Picker value={role} onChange={setRole} options={['Operations','Quality','Finance','Regulatory'].map(value=>({value,label:value+' role'}))}/><button className="iconbutton" onClick={load} aria-label="Refresh workspace"><RefreshCw size={17}/></button></div></header><main className="content"><div className="pageheading"><div><div className="eyebrow">{page==='dashboard'?'YOUR PRODUCTION, CONNECTED':'PHARMORA WORKSPACE'}</div><h1>{title}</h1><p>{page==='dashboard'?'A clear view of your manufacturing operations.':page==='audit'?'A chronological record of saved changes and workflow decisions.':module?.description}</p></div><div className="headingactions">{page==='dashboard'?<><button className="secondary" onClick={()=>nav('recalls')}><Route size={16}/>Trace a batch</button><button className="primary" onClick={()=>newForm('batches')}><Plus size={17}/>New batch</button></>:<><button className="secondary" onClick={()=>exportRows(rows)}><Download size={16}/>Export</button>{page!=='audit'&&<button className="primary" onClick={()=>newForm(page)}><Plus size={17}/>New record</button>}</>}</div></div>
{error?<div className="panel empty"><AlertTriangle/><h2>Workspace unavailable</h2><p>{error}</p><button className="primary" onClick={load}>Try again</button></div>:!state?<div className="panel empty"><RefreshCw className="spin"/><h2>Loading your workspace</h2><p>Preparing manufacturing records…</p></div>:<>
{page==='dashboard'?<>
<div className="metrics"><Metric title="Active batches" value={records.batches.filter(r=>['Planned','In production','Awaiting QC'].includes(r.status)).length} note="Across 5 manufacturing routes" icon={Factory} tone="teal"/><Metric title="Awaiting quality release" value={records.batches.filter(r=>r.status==='Awaiting QC').length} note="Quality approval required" icon={ClipboardCheck} tone="amber"/><Metric title="Inventory value" value={money(records.inventory.reduce((a,r)=>a+Number(r.quantity||0)*Number(r.cost||0),0))} note={records.inventory.length+' lots across warehouses'} icon={Boxes} tone="blue"/><Metric title="Open sales orders" value={records.sales.filter(r=>r.status==='Open').length} note={money(records.sales.filter(r=>r.status==='Open').reduce((a,r)=>a+r.quantity*r.price,0))+' awaiting dispatch'} icon={Truck} tone="violet"/></div>
<div className="overviewgrid"><section className="panel pipeline"><div className="panelhead"><div><h2>Production pipeline</h2><p>Live batch status across the plant</p></div><button className="textbutton" onClick={()=>nav('batches')}>View manufacturing<ChevronRight size={15}/></button></div><div className="pipelineSteps">{['Planned','In production','Awaiting QC','Released'].map((s,i)=><button key={s} onClick={()=>{nav('batches');setFilter(s)}}><div className={'stepicon step'+i}>{[<CalendarDays key={0}/>,<Factory key={1}/>,<FlaskConical key={2}/>,<CheckCircle2 key={3}/>][i]}</div><strong>{records.batches.filter(r=>r.status===s).length.toString().padStart(2,'0')}</strong><span>{s}</span><div className={'stagebar stage'+i}/></button>)}</div><div className="pipelineFoot"><ShieldCheck size={15}/><span>Quality approval gates protect every finished batch.</span></div></section><section className="panel attention"><div className="panelhead"><h2>Needs attention</h2><span className="countTag">{alertItems.reduce((a,x)=>a+x.count,0)}</span></div>{alertItems.map(a=><button key={a.module} className="attentionrow" onClick={()=>nav(a.module)}><span className="alertIcon"><a.icon size={18}/></span><div><strong>{a.title}</strong><small>{a.desc}</small></div><b>{a.count}</b><ChevronRight size={16}/></button>)}</section></div>
<section className="panel"><div className="panelhead"><div><h2>Batch activity</h2><p>From production planning to finished goods</p></div><button className="textbutton" onClick={()=>nav('batches')}>View all batches<ChevronRight size={15}/></button></div>{table('batches',records.batches.slice(0,5),true)}</section>
<div className="bottomgrid"><section className="panel"><div className="panelhead"><h2>Manufacturing routes</h2><span className="muted">5 configured</span></div><div className="routecards">{types.map((t,i)=><button key={t} onClick={()=>{nav('products');setType(t)}}><span className="routeNumber">0{i+1}</span><strong>{t}</strong><small>{records.products.filter(p=>p.type===t).length} product · {flows[t].length} process stages</small><ChevronRight size={17}/></button>)}</div></section><section className="panel"><div className="panelhead"><h2>Recent activity</h2><button className="textbutton" onClick={()=>nav('audit')}>View log</button></div><div className="activitylist">{state.audit.slice(0,4).map(a=><div key={a.id}><span className="activityDot"/><strong>{a.name}</strong><small>{a.role} · {new Date(a.at).toLocaleString()}</small></div>)}</div></section></div>
</>:<>
{page==='recalls'&&<section className="panel tracepanel"><div className="panelhead"><div><h2>Batch genealogy</h2><p>Source lots, quality decisions and customer destinations</p></div><Picker value={trace} onChange={setTrace} options={records.batches.map(r=>({value:r.id,label:r.id+' · '+r.name}))}/></div>{traceBatch&&<><div className="tracegrid">{[{title:'Source materials',rows:(traceBatch.consumed||[]).map((c:any)=>({label:lookup('inventory',c.lot)?.name||c.lot,sub:c.lot+' · '+fmt(c.quantity)+' consumed',module:'inventory',id:c.lot}))},{title:'Manufacturing batch',rows:[{label:traceBatch.name,sub:traceBatch.id+' · '+traceBatch.status,module:'batches',id:traceBatch.id}]},{title:'Quality & packaging',rows:[...records.qc.filter(r=>r.target===trace).map(r=>({label:r.name,sub:r.status,module:'qc',id:r.id})),...records.packaging.filter(r=>r.batch===trace).map(r=>({label:r.name,sub:r.status,module:'packaging',id:r.id}))]},{title:'Customer shipments',rows:records.sales.filter(r=>r.batch===trace&&r.status!=='Open').map(r=>({label:r.name,sub:fmt(r.quantity)+' · '+r.status,module:'sales',id:r.id}))}].map((g,i)=><div key={g.title} className="tracecolumn"><div className="traceheading"><span>{i+1}</span>{g.title}</div>{g.rows.length?g.rows.map((r:any)=><button key={r.id} onClick={()=>setSelected({module:r.module,id:r.id})}><strong>{r.label}</strong><small>{r.sub}</small></button>):<p className="muted">No records yet</p>}</div>)}</div><div className="tracefooter"><span>Batch cost <strong>{money(batchCost(traceBatch))}</strong></span><span>Available finished stock <strong>{fmt(records.inventory.filter(r=>r.batch===trace).reduce((a,r)=>a+Number(r.quantity||0),0))}</strong></span><button className="textbutton" onClick={()=>{newForm('recalls');setForm((f:any)=>({...f,data:{...f.data,batch:trace,name:'Recall assessment · '+trace}}))}}>Create recall assessment</button></div></>}</section>}
{page==='finance'&&<><div className="metrics three"><Metric title="Open receivables" value={money(records.finance.filter(r=>r.kind==='Receivable'&&r.status==='Open').reduce((a,r)=>a+Number(r.amount||0),0))} note="Awaiting customer payment" icon={Wallet} tone="teal"/><Metric title="Open payables" value={money(records.finance.filter(r=>r.kind==='Payable'&&r.status==='Open').reduce((a,r)=>a+Number(r.amount||0),0))} note="Supplier obligations" icon={ShoppingCart} tone="amber"/><Metric title="Recorded batch costs" value={money(records.batches.reduce((a,r)=>a+batchCost(r),0))} note="Materials, labour and overhead" icon={Factory} tone="blue"/></div><section className="panel costpanel"><div className="panelhead"><h2>Batch cost breakdown</h2><span className="muted">USD</span></div><Table><TableHeader><TableRow><TableHead>Batch</TableHead><TableHead>Materials</TableHead><TableHead>Labour</TableHead><TableHead>Overhead</TableHead><TableHead>Total</TableHead><TableHead>Cost / unit</TableHead></TableRow></TableHeader><TableBody>{records.batches.map(r=><TableRow key={r.id}><TableCell>{r.id}<small>{r.name}</small></TableCell><TableCell>{money((r.consumed||[]).reduce((a:number,c:any)=>a+c.cost,0))}</TableCell><TableCell>{money(r.labour)}</TableCell><TableCell>{money(r.overhead)}</TableCell><TableCell><strong>{money(batchCost(r))}</strong></TableCell><TableCell>{r.actual?'$'+(batchCost(r)/r.actual).toFixed(4):'Pending yield'}</TableCell></TableRow>)}</TableBody></Table></section></>}
{page==='planning'&&<div className="capacitygrid">{records.equipment.filter(r=>r.category==='Production equipment').map(e=>{const used=records.planning.filter(p=>p.equipment===e.id&&p.status==='Scheduled').reduce((a,p)=>a+Number(p.hours||0)+Number(p.changeover||0),0);return <div className="panel capacity" key={e.id}><strong>{e.name}</strong><small>{used} scheduled hours / {e.capacity} daily hours</small><Progress value={Math.min(100,used/(e.capacity||16)*100)}/><Status value={e.status}/></div>})}</div>}
<section className="panel"><div className="listtoolbar"><div className="searchbox"><Search size={17}/><input aria-label="Search records" placeholder={'Search '+(module?.short.toLowerCase()||'activity')+'…'} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{module&&<Picker value={filter} onChange={setFilter} options={['All',...module.statuses].map(value=>({value,label:value==='All'?'All statuses':value}))}/>} {['products','batches'].includes(page)&&<Picker value={type} onChange={setType} options={['All',...types].map(value=>({value,label:value==='All'?'All manufacturing types':value}))}/>}<span className="recordcount">{rows.length} records</span></div></div>{table(page,rows)}<div className="tablefooter"><span>{rows.length} of {(page==='audit'?state.audit:records[page]).length} records</span><span>Changes are saved to your workspace</span></div></section>
</>}
<div className="workspacefooter"><span><span className="savedDot"/>Workspace saved · Revision {version}</span><button onClick={()=>setHelp(true)}>Demo data · Prototype scope</button></div></>}
</main></SidebarInset>
<Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent className="detailsheet">{record&&selected&&<><SheetHeader><div className="eyebrow">{modules[selected.module].short} / {record.id}</div><SheetTitle>{record.name}</SheetTitle><SheetDescription><Status value={record.status}/></SheetDescription></SheetHeader><div className="sheetbody"><div className="actionbar"><button className="secondary" onClick={()=>newForm(selected.module,record)}>Edit record</button>{['products','documents'].includes(selected.module)&&<button className="secondary" onClick={()=>newForm(selected.module,record,true)}>Create revision</button>}{actions(selected.module,record).map(a=><button key={a} disabled={busy} className={['Reject','Fail','Activate recall'].includes(a)?'danger':'primary'} onClick={()=>doAction(selected.module,record,a)}>{a}</button>)}</div><Tabs defaultValue="details" key={record.id}><TabsList className="detailtabs"><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="related">Linked records</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="details">
{selected.module==='batches'&&<div className="batchsteps"><h3>Manufacturing progress</h3><Progress value={(record.step||0)/6*100}/>{(flows[lookup('products',record.product)?.type]||[]).map((s,i)=><div className={i<(record.step||0)?'complete':''} key={s}><span>{i<(record.step||0)?<Check size={14}/>:i+1}</span><div><strong>{s}</strong>{record.checks?.[i]&&<small>{record.checks[i].result}</small>}</div>{i===(record.step||0)&&record.status==='In production'&&<b>Current</b>}</div>)}</div>}
<div className="detailfields">{modules[selected.module].fields.map(f=><div key={f.key} className={f.kind==='textarea'?'wide':''}><label>{f.label}</label><p>{f.ref?lookup(f.ref,record[f.key])?.name||record[f.key]||'—':String(record[f.key]??'—')}</p></div>)}</div>{selected.module==='batches'&&<div className="costtotal">Recorded batch cost<strong>{money(batchCost(record))}</strong></div>}
</TabsContent><TabsContent value="related"><div className="linkedlist">{Object.entries(records).flatMap(([m,rs])=>rs.filter(r=>r.id!==record.id&&[r.batch,r.target,r.product,r.supplier,r.source,r.reference,r.equipment,r.material,r.plan].includes(record.id)).map(r=><button key={r.id} onClick={()=>open(m,r)}><span>{modules[m].short}</span><strong>{r.name}</strong><Status value={r.status}/></button>))}{selected.module==='batches'&&(record.consumed||[]).map((c:any)=><button key={c.lot} onClick={()=>setSelected({module:'inventory',id:c.lot})}><span>Consumed material</span><strong>{c.lot} · {fmt(c.quantity)}</strong></button>)}<p className="muted">Linked records appear as you progress through the workflow.</p></div></TabsContent><TabsContent value="history"><div className="activitylist">{state?.audit.filter(a=>a.record===record.id).map(a=><div key={a.id}><strong>{a.name}</strong><p>{a.detail}</p><small>{a.role} · {new Date(a.at).toLocaleString()}</small></div>)}<p className="muted">Seeded records have no prior approval history. New actions are recorded here.</p></div></TabsContent></Tabs></div></>}</SheetContent></Sheet>
<Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="formdialog"><DialogHeader><DialogTitle>{form?.action==='Create'?'New '+(modules[form.module]?.short.toLowerCase()||'record'):form?.action==='Edit'?'Edit record':form?.action}</DialogTitle><DialogDescription>{form?.name||'Changes will be recorded in the workspace audit history.'}</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();save(form.module,form.action,form.id,form.data)}}><div className="formfields">{['Create','Edit'].includes(form.action)?modules[form.module].fields.map(f=><FormField key={f.key} field={f} value={form.data[f.key]} records={records} onChange={v=>setForm({...form,data:{...form.data,[f.key]:v}})}/>):form.action==='Record next step'?<><label className="wide">Step observation<textarea required value={form.data.result||''} onChange={e=>setForm({...form,data:{...form.data,result:e.target.value}})} placeholder="Record process checks and observations"/></label><label>Actual output (required on final step)<input type="number" min="1" value={form.data.actual||''} onChange={e=>setForm({...form,data:{...form.data,actual:e.target.value}})}/></label></>:form.action==='Transfer'?<label className="wide">Destination warehouse / bin<input required value={form.data.location||''} onChange={e=>setForm({...form,data:{location:e.target.value}})}/></label>:<div className="wide confirmation"><ShieldCheck size={30}/><p>Confirm <strong>{form.action.toLowerCase()}</strong> for <strong>{form.name}</strong>.</p><p>The system will check the record’s prerequisites before saving this action.</p><small>Acting as: {role} demo role</small></div>}</div><div className="formfooter"><button type="button" className="secondary" onClick={()=>setForm(null)}>Cancel</button><button disabled={busy} type="submit" className="primary">{busy?'Saving…':['Create','Edit'].includes(form.action)?'Save record':'Confirm '+form.action.toLowerCase()}</button></div></form>}</DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent className="guidedialog"><DialogHeader><DialogTitle>Explore your manufacturing ERP</DialogTitle><DialogDescription>A connected prototype with persistent demonstration records.</DialogDescription></DialogHeader><div className="guide"><h3>Try an end-to-end workflow</h3><ol><li>Open Manufacturing and start the Dermacare cream batch.</li><li>Record all six process steps, including actual output on the final step.</li><li>Open its linked quality test. Edit the result, then switch to the Quality role and pass it.</li><li>Update the packaging order with artwork and clearance references, then complete reconciliation.</li><li>Release the batch as Quality. Create a sales order, dispatch it, then trace the batch.</li></ol><h3>Prototype boundaries</h3><p>All records and workflow actions are demonstrations. Roles are a switchable simulation, not employee authentication. Integrations, electronic signatures, regulatory submissions, instrument feeds and serialization networks are not connected.</p><p>Costing and accounting are simplified. Material consumption uses one primary material per formula; additional ingredient specifications are recorded as text. Sterile and API process checks are illustrative, not validated manufacturing controls.</p><p>Use demonstration data only. This prototype is not a validated system for production use.</p></div></DialogContent></Dialog>
</SidebarProvider>;
}
function Metric({title,value,note,icon:Icon,tone}:any){return <div className="metric"><div className="metrictop"><span>{title}</span><span className={'metricicon '+tone}><Icon size={18}/></span></div><strong>{value}</strong><small>{note}</small></div>}
function FormField({field:f,value,records,onChange}:{field:Field;value:any;records:Record<string,Row[]>;onChange:(v:any)=>void}){const options=f.options?.map(value=>({value,label:value}))||(f.ref?records[f.ref]?.map(r=>({value:r.id,label:r.id+' · '+r.name})):f.kind==='target'?[...(records.batches||[]),...(records.inventory||[])].map(r=>({value:r.id,label:r.id+' · '+r.name})):[]);return <label className={f.kind==='textarea'?'wide':''}>{f.label}{f.key==='name'&&' *'}{['select','ref','target'].includes(f.kind)?<Picker value={value||''} onChange={onChange} options={options||[]}/>:f.kind==='textarea'?<textarea value={value||''} onChange={e=>onChange(e.target.value)}/>:<input required={f.key==='name'} type={f.kind} min={f.kind==='number'?0:undefined} step={f.kind==='number'?'any':undefined} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
