export type Row={id:string;name:string;status:string;[key:string]:any};
export type State={records:Record<string,Row[]>;audit:Row[]};
export const types=['Tablets & capsules','Syrups & oral liquids','Creams & ointments','Sterile injectables','Active ingredients'];
export const flows:Record<string,string[]>={
[types[0]]:['Dispensing','Blending / granulation','Drying','Compression / filling','Coating','Yield reconciliation'],
[types[1]]:['Water verification','Dispensing','Mixing','Bulk holding','Filling','Volume checks'],
[types[2]]:['Phase preparation','Heating','Emulsification','Homogenization','Cooling','Tube / jar filling'],
[types[3]]:['Line clearance','Component preparation','Compounding','Filtration / sterilization','Aseptic / terminal fill','Container closure checks'],
[types[4]]:['Dispensing','Reaction','Separation','Purification','Drying','Yield reconciliation']};
export type Field={key:string;label:string;kind:string;options?:string[];ref?:string};
const f=(key:string,label:string,kind='text',options?:string[]):Field=>({key,label,kind,options});
const ref=(key:string,label:string,ref:string):Field=>({key,label,kind:'ref',ref});
export const modules:Record<string,{title:string;short:string;description:string;fields:Field[];statuses:string[]}>= {
products:{title:'Products & formulations',short:'Products',description:'Product masters, approved formulations and manufacturing routes.',fields:[f('name','Product name'),f('type','Manufacturing type','select',types),f('strength','Strength / grade'),f('version','Formula version'),f('size','Standard batch size','number'),f('unit','Output unit','select',['units','bottles','tubes','vials','kg']),ref('material','Primary material lot','inventory'),f('requiredQty','Material per standard batch','number'),f('shelfLife','Shelf life (months)','number'),f('specification','Product specification','textarea'),f('formula','Formula / ingredient quantities','textarea'),f('storage','Storage conditions')],statuses:['Draft','Approved','Obsolete']},
suppliers:{title:'Suppliers & qualification',short:'Suppliers',description:'Sourcing partners, qualification and performance.',fields:[f('name','Supplier name'),f('category','Category'),f('contact','Contact email'),f('country','Country'),f('expiry','Qualification expiry','date'),f('certificate','Certificate reference'),f('score','Performance score','number')],statuses:['Under review','Approved','Suspended']},
procurement:{title:'Procurement',short:'Procurement',description:'Purchase materials and receive traceable lots into quarantine.',fields:[f('name','Material name'),ref('supplier','Supplier','suppliers'),f('quantity','Quantity','number'),f('unit','Unit','select',['kg','L','units']),f('cost','Unit cost (USD)','number'),f('due','Expected receipt','date'),f('expiry','Expiry / retest date','date'),f('certificate','Supplier certificate reference')],statuses:['Draft','Ordered','Received']},
inventory:{title:'Inventory & warehouses',short:'Inventory',description:'Lot-level stock, locations, shelf life and quality status.',fields:[f('name','Material / product'),f('category','Category','select',['Raw material','Packaging','Intermediate','Finished goods']),f('quantity','Available quantity','number'),f('unit','Unit','select',['kg','L','units','bottles','tubes','vials']),f('location','Warehouse / bin'),ref('supplier','Supplier','suppliers'),f('expiry','Expiry / retest date','date'),f('cost','Unit cost (USD)','number'),f('storage','Storage conditions'),f('reorder','Reorder point','number')],statuses:['Quarantine','Released','Rejected','Recalled']},
planning:{title:'Production planning',short:'Planning',description:'Schedule demand against available materials and line capacity.',fields:[f('name','Plan name'),ref('product','Product','products'),f('quantity','Planned output','number'),ref('equipment','Equipment / line','equipment'),f('due','Scheduled date','date'),f('hours','Required capacity (hours)','number'),f('changeover','Cleaning / changeover hours','number')],statuses:['Draft','Scheduled','Converted']},
batches:{title:'Batch manufacturing',short:'Manufacturing',description:'Execute and review five specialized manufacturing workflows.',fields:[f('name','Batch description'),ref('product','Product','products'),f('quantity','Planned output','number'),ref('equipment','Equipment / line','equipment'),f('due','Target completion','date'),f('expiry','Finished product expiry','date'),f('labour','Labour cost (USD)','number'),f('overhead','Overhead cost (USD)','number')],statuses:['Planned','In production','Awaiting QC','Released','Rejected','Recalled']},
packaging:{title:'Packaging & labelling',short:'Packaging',description:'Artwork control, line clearance and label reconciliation.',fields:[f('name','Packaging order'),ref('batch','Manufacturing batch','batches'),f('artwork','Approved artwork reference'),f('issued','Labels issued','number'),f('used','Labels used','number'),f('rejected','Labels rejected','number'),f('returned','Labels returned','number'),f('serial','Serialization / aggregation reference'),f('clearance','Line clearance record')],statuses:['Draft','In progress','Completed']},
qc:{title:'Quality control laboratory',short:'Quality control',description:'Samples, specifications, results and stability programmes.',fields:[f('name','Sample / test name'),f('target','Batch or lot','target'),f('testType','Test type','select',['Release testing','In-process','Stability','Retained sample','Environmental monitoring']),f('specification','Acceptance specification','textarea'),f('result','Recorded result','textarea'),f('certificate','Certificate of analysis reference'),f('due','Test / stability due','date'),f('retention','Retained sample location')],statuses:['Pending','Passed','Failed']},
qa:{title:'Quality assurance',short:'Quality assurance',description:'Deviations, CAPA, change control and quality investigations.',fields:[f('name','Issue / change title'),f('kind','Record type','select',['Deviation','CAPA','Change control','Audit','Supplier quality','Complaint']),ref('batch','Related batch','batches'),f('severity','Severity','select',['Minor','Major','Critical']),f('owner','Responsible person'),f('due','Due date','date'),f('investigation','Investigation / root cause','textarea'),f('action','Corrective action / evidence','textarea')],statuses:['Open','Investigating','Closed']},
equipment:{title:'Equipment & utilities',short:'Equipment',description:'Maintenance, calibration, cleaning and facility utility records.',fields:[f('name','Asset / utility'),f('category','Category','select',['Production equipment','Water system','HVAC','Laboratory instrument','Utility']),f('line','Production area'),f('capacity','Daily capacity (hours)','number'),f('calibration','Calibration due','date'),f('maintenance','Maintenance due','date'),f('cleaning','Cleaning record'),f('service','Maintenance / utility observations','textarea')],statuses:['Ready','In use','Maintenance','Out of service']},
sales:{title:'Sales & distribution',short:'Sales orders',description:'Allocate released batches, dispatch orders and manage returns.',fields:[f('name','Customer name'),ref('product','Product','products'),ref('batch','Allocated batch','batches'),f('quantity','Order quantity','number'),f('price','Unit price (USD)','number'),f('credit','Available credit (USD)','number'),f('minShelf','Minimum shelf life (days)','number'),f('due','Delivery date','date'),f('address','Delivery address'),f('transport','Transport conditions')],statuses:['Open','Dispatched','Returned']},
recalls:{title:'Traceability & recalls',short:'Traceability',description:'Follow materials through batches to every customer shipment.',fields:[f('name','Recall / complaint title'),ref('batch','Affected batch','batches'),f('reason','Reason / assessment','textarea'),f('recovered','Recovered quantity','number'),f('disposition','Recovery / disposition evidence','textarea')],statuses:['Open','Active','Closed']},
finance:{title:'Finance & costing',short:'Finance',description:'Receivables, payables, journals and manufacturing costs.',fields:[f('name','Document description'),f('kind','Document type','select',['Receivable','Payable','Journal']),f('amount','Amount (USD)','number'),f('account','Debit account'),f('counterAccount','Credit account'),f('reference','Source reference'),f('due','Due date','date')],statuses:['Open','Paid']},
documents:{title:'Documents & training',short:'Documents',description:'Controlled procedures, revisions and employee training.',fields:[f('name','Document title'),f('kind','Type','select',['SOP','Manufacturing instruction','Training','Qualification']),f('version','Revision'),f('owner','Owner / assignee'),f('due','Review / training due','date'),f('content','Controlled content','textarea'),f('evidence','Training / qualification evidence','textarea')],statuses:['Draft','Approved','Acknowledged','Obsolete']},
regulatory:{title:'Regulatory & registrations',short:'Regulatory',description:'Market registrations, licences, labels and renewals.',fields:[f('name','Registration / licence'),ref('product','Product','products'),f('market','Market'),f('number','Registration number'),f('expiry','Renewal date','date'),f('label','Approved label reference'),f('specification','Market requirements','textarea')],statuses:['Draft','Submitted','Approved','Expired']}
};
export function seed():State {
const records:State['records']=Object.fromEntries(Object.keys(modules).map(k=>[k,[]]));
records.suppliers=[{id:'SUP-001',name:'Meridian Ingredients',status:'Approved',category:'Active ingredients',country:'Switzerland',contact:'supply@example.com',expiry:'2027-09-30',score:96},{id:'SUP-002',name:'Apex Packaging',status:'Approved',category:'Primary packaging',country:'UAE',expiry:'2027-05-01',score:91}];
const names=['Paracetamol 500 mg','Cough relief syrup','Dermacare cream 1%','Sterile saline 0.9%','Paracetamol API']; const units=['units','bottles','tubes','vials','kg'];
types.forEach((type,i)=>{
records.inventory.push({id:`LOT-10${i+1}`,name:['Paracetamol API','Syrup base','Cream base','Sodium chloride','API precursor'][i],status:'Released',category:'Raw material',quantity:1500,unit:'kg',cost:12+i*3,location:`Warehouse A / 0${i+1}`,supplier:'SUP-001',expiry:'2027-12-31',storage:'Controlled ambient',reorder:250});
records.products.push({id:`PRD-00${i+1}`,name:names[i],status:'Approved',type,version:'2.1',strength:['500 mg','100 mL','1%','0.9%','Pharma grade'][i],size:10000,unit:units[i],material:`LOT-10${i+1}`,requiredQty:100,shelfLife:24,specification:'Demonstration specification. Replace with approved specifications.',formula:'Illustrative formula only; not for manufacturing.',storage:'Controlled conditions'});
records.equipment.push({id:`EQ-00${i+1}`,name:['Tablet line T-01','Liquid line L-02','Homogenizer H-01','Sterile line S-01','Reactor R-02'][i],status:'Ready',category:'Production equipment',line:`Block ${String.fromCharCode(65+i)}`,capacity:16,calibration:'2027-03-31',maintenance:'2026-12-20',cleaning:'CLN-2026-0929 verified'});
records.batches.push({id:`BTH-260${i+1}`,name:names[i],product:`PRD-00${i+1}`,status:i===0?'Released':i===1?'Awaiting QC':'Planned',quantity:10000,actual:i<2?9800:0,equipment:`EQ-00${i+1}`,due:'2026-10-03',expiry:'2028-09-28',step:i<2?6:0,consumed:i<2?[{lot:`LOT-10${i+1}`,quantity:100,cost:100*(12+i*3)}]:[],labour:420,overhead:260,checks:i<2?flows[type].map(name=>({name,result:'Completed',at:'2026-09-28T10:00:00Z'})):[]});
});
records.inventory.push({id:'FG-2601',name:names[0],status:'Released',category:'Finished goods',quantity:7800,unit:'units',batch:'BTH-2601',product:'PRD-001',expiry:'2028-09-28',location:'Finished goods / A1',cost:1880/9800});
records.qc=[{id:'QC-001',name:'Paracetamol release panel',target:'BTH-2601',status:'Passed',testType:'Release testing',specification:'Demo acceptance panel',result:'Demo checks passed',certificate:'COA-2601'},{id:'QC-002',name:'Syrup release panel',target:'BTH-2602',status:'Pending',testType:'Release testing',specification:'Approved panel required',due:'2026-10-01'}];
records.packaging=[{id:'PKG-001',name:'Paracetamol blister packaging',batch:'BTH-2601',status:'Completed',artwork:'ART-PARA-v2',issued:10000,used:9800,rejected:100,returned:100,clearance:'LC-001'},{id:'PKG-002',name:'Syrup bottle packaging',batch:'BTH-2602',status:'Draft',issued:9800,used:9800,rejected:0,returned:0}];
records.sales=[{id:'SO-001',name:'Horizon Healthcare',product:'PRD-001',batch:'BTH-2601',status:'Dispatched',quantity:2000,price:0.8,credit:25000,minShelf:180,due:'2026-09-30',address:'Distribution Centre 2',transport:'Controlled ambient'},{id:'SO-002',name:'Atlas Medical Supply',product:'PRD-001',batch:'BTH-2601',status:'Open',quantity:3000,price:0.85,credit:20000,minShelf:180,due:'2026-10-04'}];
records.finance=[{id:'INV-001',name:'Horizon Healthcare',kind:'Receivable',status:'Open',amount:1600,account:'Accounts receivable',counterAccount:'Sales',reference:'SO-001',due:'2026-10-29'}];
records.qa=[{id:'QA-001',name:'Packaging label reconciliation review',status:'Investigating',kind:'Deviation',severity:'Minor',owner:'Dr. Sara Ahmed',due:'2026-10-02',investigation:'Count discrepancy under review.'}];
records.planning=[{id:'PLN-001',name:'October tablet replenishment',product:'PRD-001',quantity:20000,equipment:'EQ-001',status:'Scheduled',due:'2026-10-05',hours:8,changeover:2}];
records.procurement=[{id:'PO-001',name:'Paracetamol API',supplier:'SUP-001',quantity:500,unit:'kg',cost:12,status:'Ordered',due:'2026-10-02',expiry:'2028-01-31',certificate:'COA-SUP-091'}];
records.documents=[{id:'DOC-001',name:'Batch release procedure',kind:'SOP',version:'3.0',owner:'Quality assurance',status:'Approved',due:'2027-01-15',content:'Demo procedure: review batch execution, laboratory results, deviations and packaging before authorized release.'},{id:'DOC-002',name:'Aseptic gowning qualification',kind:'Qualification',version:'1.0',owner:'Amina Khan',status:'Draft',due:'2026-10-01',content:'Demonstration training assignment.'}];
records.regulatory=[{id:'REG-001',name:'Paracetamol product registration',product:'PRD-001',market:'Demo market',number:'DEMO-2026-014',status:'Approved',expiry:'2027-06-30',label:'ART-PARA-v2'}];
return {records,audit:[{id:'AUD-001',name:'Demonstration workspace initialized',status:'Recorded',at:'2026-09-29T08:00:00Z',role:'System',module:'system',record:'workspace'}]};
}
export function actions(m:string,r:Row):string[]{const a:Record<string,Record<string,string[]>>={products:{Draft:['Approve']},suppliers:{'Under review':['Approve'],Approved:['Suspend'],Suspended:['Requalify']},procurement:{Draft:['Order'],Ordered:['Receive']},inventory:{Quarantine:['Release','Reject'],Released:['Transfer']},planning:{Draft:['Schedule'],Scheduled:['Create batch']},batches:{Planned:['Start production'],'In production':['Record next step'],'Awaiting QC':['Release','Reject']},packaging:{Draft:['Start packaging'],'In progress':['Complete packaging']},qc:{Pending:['Pass','Fail']},qa:{Open:['Investigate'],Investigating:['Close']},equipment:{Ready:['Start maintenance'],Maintenance:['Return to service']},sales:{Open:['Dispatch'],Dispatched:['Return']},recalls:{Open:['Activate recall'],Active:['Close recall']},finance:{Open:['Mark paid']},documents:{Draft:['Approve'],Approved:['Acknowledge']},regulatory:{Draft:['Submit'],Submitted:['Approve']}};return a[m]?.[r.status]||[];}
export function batchCost(r:Row){return (r.consumed||[]).reduce((a:number,b:any)=>a+Number(b.cost||0),0)+Number(r.labour||0)+Number(r.overhead||0)}
const uid=(p:string)=>p+'-'+crypto.randomUUID().slice(0,8).toUpperCase();
export function mutate(source:State,input:any):State{
const s=structuredClone(source);const {module,action,role='Operations',data={},recordId}=input;if(!modules[module])throw Error('Unknown module');
const list=s.records[module],r=list.find(x=>x.id===recordId);const get=(m:string,k:string)=>s.records[m].find(x=>x.id===k);const req=(ok:any,msg:string)=>{if(!ok)throw Error(msg)};const n=(v:any)=>Number(v)||0;const add=(m:string,row:any)=>{const x={...row,id:uid(m.slice(0,3).toUpperCase())};s.records[m].unshift(x);return x;};const today=new Date().toISOString().slice(0,10);
if(action==='Create'||action==='Edit'){
req(data.name?.trim(),'A name is required');for(const f of modules[module].fields){if(f.kind==='number'&&data[f.key]!==undefined&&data[f.key]!=='')req(Number.isFinite(Number(data[f.key]))&&Number(data[f.key])>=0,`${f.label} must be zero or greater`);if(f.ref&&data[f.key])req(get(f.ref,data[f.key]),`${f.label} does not exist`);}
const clean=Object.fromEntries(modules[module].fields.filter(f=>data[f.key]!==undefined).map(f=>[f.key,f.kind==='number'?n(data[f.key]):String(data[f.key]).slice(0,10000)]));
if(action==='Create')add(module,{...clean,status:modules[module].statuses[0],step:0,checks:[]});else{req(r,'Record not found');req(['Draft','Open','Pending','Planned','Under review','Investigating','In progress','Maintenance','Active'].includes(r!.status),'Approved or executed records are locked. Create a revision instead.');Object.assign(r!,clean);}
}else{
req(r,'Record not found');req(actions(module,r!).includes(action),'Action unavailable for current status');const row=r!;
if(['Release','Reject','Pass','Fail','Approve','Close','Close recall','Return to service'].includes(action))req(role==='Quality'||(action==='Approve'&&module==='regulatory'&&role==='Regulatory'),'Switch to the Quality demo role for this approval');if(action==='Mark paid')req(role==='Finance','Switch to the Finance demo role');
switch(action){
case 'Approve':req(module!=='products'||(get('inventory',row.material)&&n(row.size)>0&&n(row.requiredQty)>0),'Set material, batch size and material quantity');row.status='Approved';break;
case 'Suspend':row.status='Suspended';break;case 'Requalify':row.status='Under review';break;
case 'Order':req(get('suppliers',row.supplier)?.status==='Approved','Supplier must be approved');req(n(row.quantity)>0,'Enter a positive quantity');row.status='Ordered';break;
case 'Receive':{req(row.expiry>today,'Set a future expiry / retest date');const lot=add('inventory',{name:row.name,status:'Quarantine',category:'Raw material',quantity:row.quantity,unit:row.unit,cost:row.cost,expiry:row.expiry,supplier:row.supplier,source:row.id,location:'Receiving / quarantine'});add('qc',{name:row.name+' incoming test',target:lot.id,status:'Pending',testType:'Release testing',specification:'Record approved acceptance criteria'});add('finance',{name:row.name+' supplier invoice',status:'Open',kind:'Payable',amount:n(row.quantity)*n(row.cost),reference:row.id,account:'Inventory',counterAccount:'Accounts payable'});row.status='Received';break;}
case 'Schedule':req(get('products',row.product)?.status==='Approved','Select an approved product');req(get('equipment',row.equipment)?.status==='Ready','Equipment must be ready');req(n(row.hours)+n(row.changeover)<=n(get('equipment',row.equipment)?.capacity),'Required hours exceed daily capacity');row.status='Scheduled';break;
case 'Create batch':add('batches',{name:get('products',row.product)?.name,product:row.product,quantity:row.quantity,equipment:row.equipment,due:row.due,expiry:'2028-09-30',status:'Planned',step:0,checks:[],plan:row.id});row.status='Converted';break;
case 'Start production':{const p=get('products',row.product);req(p?.status==='Approved','Select an approved product');const eq=get('equipment',row.equipment);req(eq?.status==='Ready','Equipment is not ready');req(eq?.calibration>=today&&eq?.maintenance>=today&&eq?.cleaning,'Equipment needs current calibration, maintenance and cleaning');req(n(row.quantity)>0,'Enter positive output');const material=get('inventory',p!.material);const qty=n(p!.requiredQty)*n(row.quantity)/n(p!.size);req(material?.status==='Released'&&material.expiry>today,'Material must be released and within expiry / retest date');req(n(material?.quantity)>=qty,'Insufficient stock');material!.quantity-=qty;row.consumed=[{lot:material!.id,quantity:qty,cost:qty*n(material!.cost)}];row.formulaVersion=p!.version;row.status='In production';eq!.status='In use';break;}
case 'Record next step':{req(data.result?.trim(),'Enter a step observation');const p=get('products',row.product)!;const steps=flows[p.type];row.checks=row.checks||[];row.checks.push({name:steps[row.step||0],result:data.result,at:new Date().toISOString(),role});row.step=(row.step||0)+1;if(row.step>=steps.length){req(n(data.actual)>0&&n(data.actual)<=n(row.quantity),'Actual yield must be positive and no greater than planned output');row.actual=n(data.actual);row.status='Awaiting QC';get('equipment',row.equipment)!.status='Ready';add('qc',{name:row.name+' release panel',target:row.id,status:'Pending',testType:'Release testing',specification:'Record approved acceptance criteria'});add('packaging',{name:row.name+' packaging',batch:row.id,status:'Draft',issued:row.actual,used:row.actual,rejected:0,returned:0});}break;}
case 'Pass':case 'Fail':req(row.result&&row.specification,'Edit test to record specifications and results');row.status=action==='Pass'?'Passed':'Failed';if(action==='Fail')add('qa',{name:'OOS investigation: '+row.name,status:'Open',kind:'Deviation',severity:'Major',batch:row.target,investigation:row.result});break;
case 'Release':{const tests=s.records.qc.filter(t=>t.target===row.id);req(tests.length&&tests.every(t=>t.status==='Passed'),'All linked quality tests must pass');req(!s.records.qa.some(q=>q.batch===row.id&&q.status!=='Closed'),'Close linked quality issues first');if(module==='batches'){const packs=s.records.packaging.filter(x=>x.batch===row.id);req(packs.length&&packs.every(x=>x.status==='Completed'),'Complete packaging reconciliation first');req(row.expiry>today,'Set future product expiry');add('inventory',{name:row.name,status:'Released',category:'Finished goods',batch:row.id,product:row.product,quantity:row.actual,unit:get('products',row.product)?.unit,expiry:row.expiry,location:'Finished goods',cost:batchCost(row)/row.actual});}row.status='Released';break;}
case 'Reject':row.status='Rejected';break;
case 'Transfer':req(data.location?.trim(),'Enter destination');row.location=data.location;break;
case 'Start packaging':req(row.artwork&&row.clearance,'Add artwork and line clearance references first');row.status='In progress';break;
case 'Complete packaging':req(n(row.issued)>0&&n(row.issued)===n(row.used)+n(row.rejected)+n(row.returned),'Issued labels must equal used + rejected + returned');row.status='Completed';break;
case 'Investigate':row.status='Investigating';break;case 'Close':req(row.investigation&&row.action,'Record investigation and corrective-action evidence');row.status='Closed';break;
case 'Start maintenance':row.status='Maintenance';break;case 'Return to service':req(row.calibration>=today&&row.maintenance>=today&&row.cleaning,'Update calibration, maintenance and cleaning');row.status='Ready';break;
case 'Dispatch':{const b=get('batches',row.batch);req(b?.status==='Released','Batch must be quality released');req(b?.product===row.product,'Batch does not match ordered product');const stock=s.records.inventory.find(i=>i.batch===row.batch&&i.status==='Released');req(n(row.quantity)>0&&n(stock?.quantity)>=n(row.quantity),'Insufficient released stock');req((Date.parse(stock!.expiry)-Date.now())/86400000>=n(row.minShelf),'Stock fails remaining shelf-life requirement');req(n(row.credit)>=n(row.quantity)*n(row.price),'Order exceeds available credit');stock!.quantity-=n(row.quantity);row.status='Dispatched';row.shipped=new Date().toISOString();add('finance',{name:row.name+' invoice',kind:'Receivable',status:'Open',amount:n(row.quantity)*n(row.price),reference:row.id,account:'Accounts receivable',counterAccount:'Sales'});break;}
case 'Return':row.status='Returned';add('inventory',{name:row.name+' returned goods',batch:row.batch,product:row.product,status:'Quarantine',category:'Finished goods',quantity:row.quantity,source:row.id,location:'Returns quarantine',expiry:get('batches',row.batch)?.expiry});add('finance',{name:row.name+' credit note',kind:'Journal',status:'Open',amount:n(row.quantity)*n(row.price),reference:row.id,account:'Sales returns',counterAccount:'Accounts receivable'});break;
case 'Activate recall':req(get('batches',row.batch),'Select a batch');req(row.reason,'Enter recall reason');get('batches',row.batch)!.status='Recalled';s.records.inventory.filter(i=>i.batch===row.batch).forEach(i=>i.status='Recalled');row.status='Active';break;
case 'Close recall':req(row.disposition,'Enter recovery and disposition evidence');row.status='Closed';break;
case 'Mark paid':row.status='Paid';break;case 'Acknowledge':req(row.content,'Document content required');row.status='Acknowledged';row.acknowledgedBy=role;break;
case 'Submit':req(row.market&&row.number,'Enter market and registration number');row.status='Submitted';break;
}}
s.audit.unshift({id:uid('AUD'),name:`${action} · ${r?.name||data.name}`,status:'Recorded',at:new Date().toISOString(),role,module,record:r?.id||s.records[module][0].id,detail:data.result||data.location||''});return s;
}
